Add feed
IrinaSlipchenko/java-filmorate pull request #13
Opened 2022-07-22 13:34 UTC by OlgaEk

Лента отзывов

2022-07-22 20:31 UTC, gityanizamovramil requested changes

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleNoSuchReviewIdException (final NoSuchIdException e) {
здесь лучше переименовать метод и посмотреть какие еще методы он дублирует (возможно стоит также привести exception и методы к ним к единообразию, но это не точно)

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS review_like
будет лучше если первичный ключ идет первым при написании кода на создание таблицы

2022-07-22 20:31 UTC, gityanizamovramil commented on db/filmorate.trace.db
> +2022-07-22 10:07:54 jdbc[3]: exception
будет лучше убрать файлы или папку db в gitignor: это уменьшить конфликты при слиянии и не будет засорять репозиторий в гите.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
>      private String operation; // одно из значениий REMOVE, ADD, UPDATE
здесь можно воспользоваться enum, чтобы точно

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +import javax.validation.constraints.Pattern;
здесь если эта библиотека не используется, ее лучше убрать

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
>  import java.time.LocalDateTime;
здесь если эта библиотека не используется ее лучше убрать

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          filmStorage.update(film);
здесь внутри if clause лучше добавить return film, иначе здесь два раза обновляется film.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          film.getLikes().remove(user.getId());
здесь можно добавить проверку на то что лайк вообще присутствует в film, чтобы остановить дальнейшие манипуляции со сторедж.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          film.getLikes().add(user.getId());
здесь лучше сразу проверить есть ли такой like у фильма, чтобы далее не производить манипуляций со сторедж.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            feedDbStorage.add(Feed.builder()
будет лучше если feedDbStorage возьмет на себя всю заботу о создании объекта Feed, т.е. в feedDbStorage определить конкретные методы для каждого нужного случая. Все таки сервис это больше про бизнес логику.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        feedDbStorage.add(Feed.builder()
здесь тоже лучше предусмотреть отдельный метод для фидсторедж. Сервис не должен знать деталей сторедж.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
здесь почему то появился autowired. Должен быть RequiredArgsConctructor, не?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        review.setUserId(reviewDbStorage.get(review.getReviewId()).getUserId());
здесь будет лучше проверить что id фильма и юзера соответствуют id отзыва вместо вытягивания их значений из базы.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            feedDbStorage.add(Feed.builder()
здесь вот этот участок кода лучше спрятать в отдельном методе фидсторедж.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
лучше вернуть юзера также внутри условия "если"

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          user.getFriends().add(friendId);
здесь лучше проверить что друг уже добавлен в user, до того как мы будем обращаться в БД далее.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        feedDbStorage.add(Feed.builder()
здесь лучше бы отдельный метод для фидсторедж

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          user.getFriends().remove(friendId);
здесь лучше сразу проверить сначала что такой друг есть.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
здесь так и хочется перекинуть этот метод во френдсторедж

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FeedDbStorage.java
>          KeyHolder keyHolder = new GeneratedKeyHolder();
public Feed add (Feed feed) ..... мысли такие:
1) лучше для каждого отдельного действия завести отдельный метод. Это удобнее при написании класса сервисов, когда придется расширять бизнес-логику.
2) ты можешь создать класс-фабрику по производству нужных тебе моделей feed и здесь уже вызывать то что тебе нужно, если не хочешь много кода в сторедж.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FeedDbStorage.java
```
public List<Feed> get (Long user_id){
        final String sql = "SELECT * FROM feed WHERE user_id = ? ORDER BY event_time ASC";
        return jdbcTemplate.query(sql,this::mapRowToFeed, user_id);
    }
```
почему решила использовать ORDER BY ... ASC ? обычно в реальной жизни интересуют ведь последние обновления, а не "бородатые" события? или это все тесты постман?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FeedDbStorage.java
> +                .timestamp(rs.getTimestamp("event_time").getTime())
можешь объяснить эту строку кода пожалуйста, что из чего берется и что получается в итоге?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> -                .timestamp(LocalDateTime.now())
стоит подумать над тем, чтобы придерживаться одной линии. То есть либо фидсторедж вызывается внутри других стореджей, либо выносится на уровень сервисов. При нарастании кода и новых задач наличие фидсторедж на разных уровнях может привести к путанице.

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>                  .build());
лучше создание feed вынести в фидсторедж и добавить в фидсторедж соответстующие методы

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          return get(review.getReviewId());
зачем здесь get ? для обновления поля useful ?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>      }
здесь точно вернется поле useful?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          feedDbStorage.add(Feed.builder()
писал выше про это

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          String sql = "DELETE FROM reviews WHERE review_id = ?";
`Review review = get(reviewId);`
Это точно здесь нужно?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          feedDbStorage.add(Feed.builder()
писал про это выше

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +                + " WHERE r.film_id = ? GROUP BY (r.review_id) ORDER BY uset DESC LIMIT ?";
объясни пожалуйста, почему решила здесь использовать здесь SUM из возможных вариантов?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +        final String sql = "SELECT review_id FROM reviews WHERE review_id = ?";
здесь кстати можешь попробовать вариант с EXIST и SELECT 1

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          }
для чего это используется вообще?

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          return false;
не совсем понятно назначение этого кода, когда есть такие же методы reviewLikeDbStorage

2022-07-22 20:31 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewLikeDbStorage.java
> +        final String sql = "SELECT review_id FROM review_like WHERE review_id = ? AND user_id = ? AND is_useful = ?";
можно еще exists + select 1

2022-07-22 21:01 UTC, e-popov-lst commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +                + " WHERE r.film_id = ? GROUP BY (r.review_id) ORDER BY uset DESC LIMIT ?";
Выражение во фразе GROUP BY не надо брать в скобки. Не критично (работать будет).

2022-07-23 05:25 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleNoSuchReviewIdException (final NoSuchIdException e) {
Нет этот метод существует сам по себе и больше нигде не используется.
Переименовала

2022-07-23 05:26 UTC, OlgaEk commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS review_like
Переместила

2022-07-23 05:30 UTC, OlgaEk commented on db/filmorate.trace.db
> +2022-07-22 10:07:54 jdbc[3]: exception
Добавила

2022-07-23 06:08 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
>      private String operation; // одно из значениий REMOVE, ADD, UPDATE
Отлично. Заменила, смотрится гораздо лучше.

2022-07-23 06:13 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +import javax.validation.constraints.Pattern;
Убрала

2022-07-23 06:13 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
>  import java.time.LocalDateTime;
убрала

2022-07-23 06:13 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          filmStorage.update(film);
добавила else

2022-07-23 06:15 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          film.getLikes().remove(user.getId());
Это код Ирины. Надо обратиться к ней с вопросом о возможности здесь проведения проверки.

2022-07-23 06:16 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          film.getLikes().add(user.getId());
Это код Ирины. Надо обратиться к ней с вопросом о возможности здесь проведения проверки.

2022-07-23 06:17 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            feedDbStorage.add(Feed.builder()
Отлично. Заменила, смотрится гораздо лучше.

2022-07-23 06:17 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        feedDbStorage.add(Feed.builder()
Отлично. Заменила, смотрится гораздо лучше.

2022-07-23 06:18 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
Изменила

2022-07-23 06:23 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        review.setUserId(reviewDbStorage.get(review.getReviewId()).getUserId());
Я считаю, что в данном методе предполагается update отзыва по id отзыва ( и обновляет только определенные строки, остальные игнорирует). И получится лишняя проверка: если не соответствует, то забрать из базы верные значения.

2022-07-23 06:33 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            feedDbStorage.add(Feed.builder()
Мне кажется это неправильно. Должна быть проверка, что мы не можем обновлять дружбу и лайка(там нечего обновлять, только добавить/удалить), но это относится к коду Ирины, и надо обсуждать с ней такую возможность. Здесь я добавила проверку, чтобы не было много записей по добавлению одного и того же. 
Функционал проверки наличия записи в записи БД не относящейся к feed, переносить в feed я считаю лишним

2022-07-23 06:34 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
Я добавила else  и все стало на свои места.

2022-07-23 06:35 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          user.getFriends().add(friendId);
Это код Ирины. Надо обратиться к ней с вопросом о возможности здесь проведения проверки.

2022-07-23 06:35 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        feedDbStorage.add(Feed.builder()
Заменила.

2022-07-23 06:35 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          user.getFriends().remove(friendId);
Это код Ирины. Надо обратиться к ней с вопросом о возможности здесь проведения проверки.

2022-07-23 06:35 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
Заменила

2022-07-23 06:36 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FeedDbStorage.java
>          KeyHolder keyHolder = new GeneratedKeyHolder();
Создала отдельные методы для каждой сущности. И в методе добавления события , передается производимая операция

2022-07-23 06:37 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FeedDbStorage.java
Это последовательность событий, которая происходила в порядке хронологии. И так требуют тесты postman

2022-07-23 06:41 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FeedDbStorage.java
> +                .timestamp(rs.getTimestamp("event_time").getTime())
Тесты postman  предполагают, что в возвращаемом json должна быть числовая переменная ( или как там указана Date, но возвращать только дату странно). Поэтому у меня данные в объекте feed лежат, как тип Long ( количество миллисекунд), а уже в БД записываются как timestamp

2022-07-23 06:43 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> -                .timestamp(LocalDateTime.now())
Решения, используемые Ириной (при обновлении лайков или друзей обновляется полностью фильм или пользователь) не предполагает перенесение записи в Ленту событий на уровень ниже.

2022-07-23 06:43 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>                  .build());
Изменила

2022-07-23 06:45 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          return get(review.getReviewId());
Что бы вернуть пользователю обновленную запись

2022-07-23 06:48 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          return get(review.getReviewId());
Да что бы пользователь увидел полностью обновленную запись со всеми данными

2022-07-23 06:50 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>      }
Да оно присваивается строкой выше

2022-07-23 06:51 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          feedDbStorage.add(Feed.builder()
функцию add изменила

2022-07-23 06:55 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          String sql = "DELETE FROM reviews WHERE review_id = ?";
Да для получения id  пользователя создавшего отзыв, для записи в Ленту событий

2022-07-23 06:55 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          feedDbStorage.add(Feed.builder()
заменила add

2022-07-23 06:57 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +                + " WHERE r.film_id = ? GROUP BY (r.review_id) ORDER BY uset DESC LIMIT ?";
Если поле не заполнено БД выдается что rl.is_useful  = false  и присваивается неправильный рейтинг. А должно быть если поле rl.is_useful пустое то рейтинг 0

2022-07-23 06:58 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +                + " WHERE r.film_id = ? GROUP BY (r.review_id) ORDER BY uset DESC LIMIT ?";
Скобки убрала.

2022-07-23 06:58 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +        final String sql = "SELECT review_id FROM reviews WHERE review_id = ?";
Что ты имеешь ввиду. Мне надо проверить есть ли запись и от этого вернуть true или false

2022-07-23 07:06 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          }
Убрала .

2022-07-23 07:08 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
>          return false;
Прокомментировала в slack. Я изменила delete, после комментария наставника.

2022-07-23 07:08 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewLikeDbStorage.java
> +        final String sql = "SELECT review_id FROM review_like WHERE review_id = ? AND user_id = ? AND is_useful = ?";
Поясни, пожалуйста

2022-07-23 07:44 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleNoSuchReviewIdException (final NoSuchIdException e) {
Посмотри пожалуйста, похоже ты исправила опечатку в другом методе, и здесь название метода осталось как прежде

2022-07-23 07:45 UTC, gityanizamovramil commented on db/filmorate.trace.db
> +2022-07-22 10:07:54 jdbc[3]: exception
почему то не работает, посмотри еще раз пожалуйста

2022-07-23 08:07 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          film.getLikes().remove(user.getId());
@IrinaSlipchenko что скажешь на этот счет?

2022-07-23 08:08 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          film.getLikes().add(user.getId());
@IrinaSlipchenko посмотри пожалуйста

2022-07-23 08:13 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        review.setUserId(reviewDbStorage.get(review.getReviewId()).getUserId());
тогда отправивший такой запрос на эндпоинт может не заметить что ему подменили данные filmid, userid, как думаешь?

2022-07-23 08:16 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            feedDbStorage.add(Feed.builder()
да, ты правильно говоришь. здесь участок кода был захвачен чуть выше только чтобы было видно где нужно поменять `feedDbStorage.add(Feed.builder()`

2022-07-23 08:17 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          user.getFriends().add(friendId);
@IrinaSlipchenko еще вот здесь

2022-07-23 08:18 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          user.getFriends().remove(friendId);
@IrinaSlipchenko можешь прокомментировать, пожалуйста

2022-07-23 08:32 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +        final String sql = "SELECT review_id FROM reviews WHERE review_id = ?";
имеется ввиду, лучше использовать exist +select 1, чтобы поиск остановился сразу как условие будет выполнено.
Вот пример:
![image](https://user-images.githubusercontent.com/99643858/180597342-3aab81e0-b088-407c-87a3-5e3d68430933.png)

2022-07-23 08:36 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewLikeDbStorage.java
> +        final String sql = "SELECT review_id FROM review_like WHERE review_id = ? AND user_id = ? AND is_useful = ?";
выше отписался

2022-07-23 08:48 UTC, OlgaEk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        review.setUserId(reviewDbStorage.get(review.getReviewId()).getUserId());
Запррс обновления не предполагают замену установочных данных, они игнорируются. Если выдавать ошибку то тесты упадут

2022-07-23 15:19 UTC, gityanizamovramil approved these changes

2022-07-23 18:13 UTC, IrinaSlipchenko approved these changes

2022-07-23 18:15 UTC, merged