Add director
IrinaSlipchenko/java-filmorate pull request #14
Opened 2022-07-23 16:56 UTC by IrinaSlipchenko

2022-07-23 20:03 UTC, gityanizamovramil requested changes

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ErrorResponse(e.getMessage());
здесь опечатка handle**NoSuchNoSuch**ReactFind

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleNoSuchReviewIdException(final NoSuchReviewIdException e) {
здесь нужно решить что делать с названием метода. У Ольги он переименован.

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private TreeSet<Genre> genres;
насколько помню Сережа менял здесь на Sorted. Скорее всего у тебя старая версия. Перепроверь, пожалуйста, этот момент

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/model/SortParam.java
> +}
Почему решила использовать названия year, likes с нижним регистром? Это как-то влияет на запрос? Обычно правда enum используется с заглавными буквами.

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/resources/schema.sql
> -    primary key (review_id, user_id)
тебе нужно либо сделать rebase, либо добавить у себя недостающий код.
CREATE TABLE IF NOT EXISTS review_like
(
    review_id BIGINT REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    is_useful BOOLEAN,
    primary key (review_id, user_id)
    );

CREATE TABLE IF NOT EXISTS feed
(
    event_time TIMESTAMP NOT NULL,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    event_type VARCHAR(10) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    event_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    CONSTRAINT constr_type CHECK (event_type IN ('LIKE','REVIEW','FRIEND')),
    CONSTRAINT constr_operation CHECK (operation IN ('REMOVE','ADD','UPDATE'))
)

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS friends, film_directors, film_likes, film_genre, genres, films, directors, rating_mpa, users;
разберись, пожалуйста, со schema.sql . Возьми последний вариант после правок Оли и на его основе добавь все что тебе нужно.

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +    public TreeSet<Genre> getGenresByFilmId(Long id) {
здесь меняли на SortedSet, исправь у себя тоже

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +            film.setGenres(new TreeSet<>());
Посмотри пожалуйста какой код был у Сережи

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/resources/schema.sql
> +    film_id     BIGINT REFERENCES films (film_id),
почему film_id не обозначен как ON DELETE CASCADE ?

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    public Director create(Director director) {
странно что здесь отсутствует проверка того, что такой режиссер уже существует.

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return film;
здесь нужно посмотреть еще раз как возвращать фильм, убедиться что в findFilmById(film.getId()); не защита какая дополнительная логика

2022-07-23 20:03 UTC, gityanizamovramil commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +                "                ORDER BY COUNT(USER_ID) DESC";
как будет работать обработка такого запроса методом  `private Film mapRowToFilm(ResultSet rs, int i) throws SQLException ` если у фильма несколько режиссеров?

2022-07-24 08:10 UTC, IrinaSlipchenko commented on src/main/resources/schema.sql
> -    primary key (review_id, user_id)
Обновила у себя полностью схему( последняя схема Ольги, плюс мои две таблицы directors,  film_directors.

2022-07-24 08:32 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleNoSuchReviewIdException(final NoSuchReviewIdException e) {
Исправила,  теперь у меня точно так как у Ольги.

2022-07-24 08:34 UTC, IrinaSlipchenko commented on src/main/resources/schema.sql
> +    film_id     BIGINT REFERENCES films (film_id),
Исправила.

2022-07-24 08:37 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/model/SortParam.java
> +}
Да, влияет на запрос.  Не могу сделать заглавными буквами.

2022-07-24 08:38 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ErrorResponse(e.getMessage());
Исправила.

2022-07-24 08:49 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return film;
Проверила, все нормально. Раньше метод public Film update(Film **film**) возвращал фильм из базы : return findFilmById(film.getId());  Сейчас этот метод возвращает то, что ему прислали на вход return **film**;

2022-07-24 11:15 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private TreeSet<Genre> genres;
Исправила

2022-07-24 11:16 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmGenreDbStorage.java
> +            film.setGenres(new TreeSet<>());
Исправила у себя

2022-07-24 12:38 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    public Director create(Director director) {
Проверка не нужна.

2022-07-24 15:04 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +                "                ORDER BY COUNT(USER_ID) DESC";
Все правильно будет работать.

2022-07-25 06:05 UTC, gityanizamovramil approved these changes

2022-07-25 07:33 UTC, merged