added picture with diagram
IrinaSlipchenko/java-filmorate pull request #5
Opened 2022-07-15 14:19 UTC by IrinaSlipchenko

2022-07-15 14:45 UTC, sergey-oreshkin requested changes
**таблица фильмов**
- поле  __rating_mpa__  должно ссылаться на таблицу рейтингов
- поле  __genre__  лишнее

**таблица юзеров**
- поле __friendship__ лишнее

**первичные ключи в сводных таблицах**
в сводных таблицах (таких как film_genre, film_likes) следует делать составными, то есть состоящими из двух полей сразу, это избавить от необходимости создавать лишнее поле в них и в то же время обеспечит достаточную уникальность.

**таблица друзей**
- первичный ключ также можно сделать составным
- если правильно назвать поля(например user и friend), то станет очевидно что поле статус можно вычислить, а это нарушение нормальных форм.
приведу пример. у нас есть Петя и Вася. когда Вася добавит Петю в друзья, то в таблице появится запись - user : Вася, friend : Петя. А когда Петя добавит в друзья Васю (или подтвердит дружбу), то в таблице появится запись - user : Петя, friend : Вася
Таким образом две записи в таблице однозначно определяют подтвержденную дружбу, а одна запись - не подтвержденную, что и является значением поля status
Конечно можно реализовать более сложный механизм добавления друзей, где нужно два действия в обе стороны (запрос и подтверджение) и тогда поле статус будет нужно, но не в этом проекте ))

2022-07-16 13:01 UTC, sergey-oreshkin approved these changes
все ок

2022-07-18 18:13 UTC, avfyodorov reviewed
Добрый вечер! 
Учитывая Ваши пожелания, к мелочам придираться не стал, но вот эту штуку нужно всё-таки сделать. 
Серьёзное замечание только одно: одна таблица базы данных - один класс для выполнения базовых операций с этой таблицей.

2022-07-18 18:13 UTC, avfyodorov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "DELETE FROM film_genre WHERE film_id=?";
Это не очень удачное решение-прямой доступ к чужой таблице. По идее, данный класс должен работать только и исключительно со своей таблицей. Лучше было бы выделить методы изменения таблицы "Фильмы-Жанры" в отдельный класс.

модификация данных в таблице должны происходить исключительно и только в соответствующем классе. 
Принцип такой: одна таблица- один класс для добавления, удаления, изменения данных в этой таблице.

2022-07-19 07:51 UTC, IrinaSlipchenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "DELETE FROM film_genre WHERE film_id=?";
Исправила замечания

2022-07-19 08:30 UTC, avfyodorov reviewed
Добрый день!

Замечаний нет.
Работа принята.

2022-07-19 08:53 UTC, merged